export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAILED = "GET_BLOGS_FAILED";

export const WRITE_BLOG_REQUEST = "WRITE_BLOG_REQUEST";
export const WRITE_BLOG_SUCCESS = "WRITE_BLOG_SUCCESS";
export const WRITE_BLOG_FAILED = "WRITE_BLOG_FAILED";
